# Five Vault Template
# A native SOL vault example

[project]
name = "five-vault-template"
version = "0.1.0"
description = "A native SOL vault example"
source_dir = "src"
build_dir = "build"
target = "vm"
entry_point = "src/main.v"

[build]
output_artifact_name = "five-vault-template"


[optimizations]
enable_compression = true
enable_constraint_optimization = true
optimization_level = 2
