// Generated by five template
// Starter template in Five DSL. Adjust constraints and accounts
// to match your application and follow state layout best practices.

// Escrow template: maker locks funds for a designated taker

account EscrowState {
    maker: pubkey;
    taker: pubkey;
    amount: u64;
    is_funded: bool;
    is_settled: bool;
}

pub init_escrow(state: EscrowState @mut, maker: account @signer, taker: pubkey, amount: u64) {
    state.maker = maker.ctx.key;
    state.taker = taker;
    state.amount = amount;
    state.is_funded = false;
    state.is_settled = false;
}

pub fund_escrow(state: EscrowState @mut, maker: account @signer, amount: u64) {
    require(state.maker == maker.ctx.key);
    require(amount == state.amount);
    state.is_funded = true;
}

pub claim_escrow(state: EscrowState @mut, taker: account @signer) {
    require(state.is_funded);
    require(!state.is_settled);
    require(state.taker == taker.ctx.key);
    state.is_settled = true;
}

pub cancel_escrow(state: EscrowState @mut, maker: account @signer) {
    require(!state.is_settled);
    require(state.maker == maker.ctx.key);
    state.is_funded = false;
}

// Reset escrow state (for demo/testing)
pub reset(state: EscrowState @mut) {
    state.is_funded = false;
    state.is_settled = false;
}

// Read-only helper: whether escrow is claimable
pub is_claimable(state: EscrowState) -> bool {
    return (state.is_funded) && (!state.is_settled);
}
