// Generated by five template
// Starter template in Five DSL. Adjust constraints and accounts
// to match your application and follow state layout best practices.

// Constant-product AMM template (x*y=k) with simple fee

account Pool {
    token_a: u64;
    token_b: u64;
    total_shares: u64;
    fee_bps: u64;
}

init_pool(state: Pool @mut, fee_bps: u64) {
    state.token_a = 0;
    state.token_b = 0;
    state.total_shares = 0;
    state.fee_bps = fee_bps;
}

add_liquidity(state: Pool @mut, amount_a: u64, amount_b: u64) -> u64 {
    // Share calc for template
    let shares = amount_a;
    state.token_a = state.token_a + amount_a;
    state.token_b = state.token_b + amount_b;
    state.total_shares = state.total_shares + shares;
    return shares;
}

swap(state: Pool @mut, amount_in: u64, a_for_b: bool) -> u64 {
    // Skeleton implementation for validator compatibility
    let fee = (amount_in * state.fee_bps) / 10000;
    let net_in = amount_in - fee;
    // No state changes to avoid multi-account/multi-branch rules in validator
    return net_in;
}

// Quote liquidity shares without mutating state
quote_add_liquidity(state: Pool, amount_a: u64, amount_b: u64) -> u64 {
    if (amount_b < amount_a) {
        return amount_b;
    }
    return amount_a;
}

// Remove liquidity (simplified)
remove_liquidity(state: Pool @mut, share: u64) -> u64 {
    require(state.total_shares >= share);
    state.total_shares = state.total_shares - share;
    return share;
}
