// Generated by five template
// Starter template in Five DSL. Adjust constraints and accounts
// to match your application and follow state layout best practices.

// NFT template with simple mint and transfer

account NFT {
    token_id: pubkey;
    owner_key: pubkey;
    uri: string<128>;
}

// Initialize NFT fields
pub mint_nft(state: NFT @mut, owner: pubkey, uri: string<128>) {
    // For template simplicity, assign token_id deterministically
    state.token_id = owner;
    state.owner_key = owner;
    state.uri = uri;
}

// Transfer ownership
pub transfer_nft(state: NFT @mut, from: pubkey, to: pubkey) {
    require(state.owner_key == from);
    state.owner_key = to;
}

// Update token metadata URI
pub set_uri(state: NFT @mut, owner: pubkey, new_uri: string<128>) {
    require(state.owner_key == owner);
    state.uri = new_uri;
}

// Read-only helpers
pub get_uri(state: NFT) -> string<128> { return state.uri; }
pub get_owner(state: NFT) -> pubkey { return state.owner_key; }
