// Generated by five template
// Starter template in Five DSL. Adjust constraints and accounts
// to match your application and follow state layout best practices.

// NFT template with simple mint and transfer

account NFT {
    token_id: pubkey;
    owner_key: pubkey;
    uri: string;
}

// Initialize NFT fields
mint_nft(state: NFT @mut, owner: pubkey, uri: string) {
    // For template simplicity, assign token_id deterministically
    state.token_id = owner;
    state.owner_key = owner;
    state.uri = uri;
}

// Transfer ownership
transfer_nft(state: NFT @mut, from: pubkey, to: pubkey) {
    require(state.owner_key == from);
    state.owner_key = to;
}

// Update token metadata URI
set_uri(state: NFT @mut, owner: pubkey, new_uri: string) {
    require(state.owner_key == owner);
    state.uri = new_uri;
}

// Read-only helpers
get_uri(state: NFT) -> string { return state.uri; }
get_owner(state: NFT) -> pubkey { return state.owner_key; }
