// Generated by five template
// This template is designed to be more like an SPL token,
// incorporating common features and security best practices.

// Fungible token template with advanced mint, transfer, and authority management

account Mint {
    authority: pubkey; // Minting authority
    freeze_authority: pubkey; // Authority to freeze token accounts
    supply: u64;
    decimals: u8;
}

account TokenAccount {
    owner_key: pubkey;
    mint: pubkey; // The mint this token account belongs to
    bal: u64;
    is_frozen: bool; // Indicates if this token account is frozen
}

// Initialize mint state
pub init_mint(
    state: Mint @mut,
    authority: account @signer,
    freeze_authority: pubkey,
    decimals: u8
) {
    state.authority = authority.ctx.key;
    state.freeze_authority = freeze_authority;
    state.supply = 0;
    state.decimals = decimals;
}

// Initialize a token account
pub init_account(
    state: TokenAccount @mut,
    owner: account @signer,
    mint: pubkey
) {
    state.owner_key = owner.ctx.key;
    state.mint = mint;
    state.bal = 0;
    state.is_frozen = false;
}

// Create an Associated Token Account (ATA) for an owner and mint
pub create_associated_token_account(
    ata_account: TokenAccount @mut @init, // @init constraint creates the account
    owner: account @signer,
    mint: pubkey
) {
    // In a real implementation, the ATA address would be derived here using PDA:
    // let (ata_address, bump_seed) = derive_pda([owner, mint], program_id);
    // require(ata_account.ctx.key == ata_address);

    // Initialize the newly created ATA
    init_account(ata_account, owner, mint);
}

// Mint new tokens and deposit into a token account
pub mint_to(
    mint_state: Mint @mut,
    destination_account: TokenAccount @mut,
    mint_authority: account @signer,
    amount: u64
) {
    require(mint_state.authority == mint_authority.ctx.key);
    require(!destination_account.is_frozen);
    require(amount > 0);

    mint_state.supply = mint_state.supply + amount;
    destination_account.bal = destination_account.bal + amount;
}

// Transfer tokens from source to destination
pub transfer(
    source_account: TokenAccount @mut,
    destination_account: TokenAccount @mut,
    owner: account @signer,
    amount: u64
) {
    require(source_account.owner_key == owner.ctx.key);
    require(source_account.bal >= amount);
    require(source_account.mint == destination_account.mint);
    require(!source_account.is_frozen);
    require(!destination_account.is_frozen);
    require(amount > 0);

    source_account.bal = source_account.bal - amount;
    destination_account.bal = destination_account.bal + amount;
}

// Burn tokens from a token account
pub burn(
    mint_state: Mint @mut,
    source_account: TokenAccount @mut,
    owner: account @signer,
    amount: u64
) {
    require(source_account.owner_key == owner.ctx.key);
    require(source_account.bal >= amount);
    require(!source_account.is_frozen);
    require(amount > 0);

    mint_state.supply = mint_state.supply - amount;
    source_account.bal = source_account.bal - amount;
}

// Freeze a token account
pub freeze_account(
    mint_state: Mint,
    account_to_freeze: TokenAccount @mut,
    freeze_authority: account @signer
) {
    require(mint_state.freeze_authority == freeze_authority.ctx.key);
    account_to_freeze.is_frozen = true;
}

// Thaw a token account
pub thaw_account(
    mint_state: Mint,
    account_to_thaw: TokenAccount @mut,
    freeze_authority: account @signer
) {
    require(mint_state.freeze_authority == freeze_authority.ctx.key);
    account_to_thaw.is_frozen = false;
}

// Close a token account and reclaim rent (owner must be signer)
pub close_account(
    source_account: TokenAccount @mut,
    owner: account @signer
) {
    require(source_account.owner_key == owner.ctx.key);
    require(source_account.bal == 0);
    // In a real VM, this would involve transferring lamports back and marking account as closed/uninitialized
    // Set balance to 0 and conceptually "close" it.
    source_account.bal = 0;
}

// Change mint authority
pub set_mint_authority(
    mint_state: Mint @mut,
    current_authority: account @signer,
    new_authority: pubkey
) {
    require(mint_state.authority == current_authority.ctx.key);
    mint_state.authority = new_authority;
}

// Change freeze authority
pub set_freeze_authority(
    mint_state: Mint @mut,
    current_freeze_authority: account @signer,
    new_freeze_authority: pubkey
) {
    require(mint_state.freeze_authority == current_freeze_authority.ctx.key);
    mint_state.freeze_authority = new_freeze_authority;
}

// Read-only helpers
pub get_supply(state: Mint) -> u64 { return state.supply; }
pub get_balance(state: TokenAccount) -> u64 { return state.bal; }
pub is_account_frozen(state: TokenAccount) -> bool { return state.is_frozen; }

// Note on Associated Token Accounts (ATAs):
// In a full SPL-like implementation, TokenAccount addresses are often derived
// using a PDA (Program Derived Address) from the owner's pubkey and the mint's pubkey.
// This would typically involve a 'derive_pda' function call during account initialization
// and lookup. The current 'TokenAccount' is a direct account for simplicity.
