// Generated by five template
// This template is designed to be more like an SPL token,
// incorporating common features and security best practices.

// Fungible token template with advanced mint, transfer, and authority management

account Mint {
    authority: pubkey; // Minting authority
    freeze_authority: pubkey; // Authority to freeze token accounts
    supply: u64;
    decimals: u8;
}

account TokenAccount {
    owner_key: pubkey;
    mint: pubkey; // The mint this token account belongs to
    bal: u64;
    is_frozen: bool; // Indicates if this token account is frozen
}

// Initialize mint state
init_mint(
    state: Mint @mut,
    authority: pubkey @signer,
    freeze_authority: pubkey,
    decimals: u8
) {
    state.authority = authority;
    state.freeze_authority = freeze_authority;
    state.supply = 0;
    state.decimals = decimals;
}

// Initialize a token account
init_account(
    state: TokenAccount @mut,
    owner: pubkey @signer,
    mint: pubkey
) {
    state.owner_key = owner;
    state.mint = mint;
    state.bal = 0;
    state.is_frozen = false;
}

// Create an Associated Token Account (ATA) for an owner and mint
create_associated_token_account(
    ata_account: TokenAccount @mut @init, // @init constraint creates the account
    owner: pubkey @signer,
    mint: pubkey
) {
    // In a real implementation, the ATA address would be derived here using PDA:
    // let (ata_address, bump_seed) = derive_pda([owner, mint], program_id);
    // require(get_key(ata_account) == ata_address, "ATA address mismatch");

    // Initialize the newly created ATA
    init_account(ata_account, owner, mint);
}

// Mint new tokens and deposit into a token account
mint_to(
    mint_state: Mint @mut,
    destination_account: TokenAccount @mut,
    mint_authority: account @signer,
    amount: u64
) {
    require(mint_state.authority == mint_authority, "Mint authority mismatch");
    require(destination_account.mint == get_key(mint_state), "Destination account mint mismatch"); // Ensure destination is for this mint
    require(!destination_account.is_frozen, "Destination account is frozen");

    mint_state.supply = mint_state.supply + amount;
    destination_account.bal = destination_account.bal + amount;
}

// Transfer tokens from source to destination
transfer(
    source_account: TokenAccount @mut,
    destination_account: TokenAccount @mut,
    owner: pubkey @signer,
    amount: u64
) {
    require(source_account.owner_key == owner, "Source account owner mismatch");
    require(source_account.bal >= amount, "Insufficient balance");
    require(source_account.mint == destination_account.mint, "Mint mismatch between accounts");
    require(!source_account.is_frozen, "Source account is frozen");
    require(!destination_account.is_frozen, "Destination account is frozen");

    source_account.bal = source_account.bal - amount;
    destination_account.bal = destination_account.bal + amount;
}

// Burn tokens from a token account
burn(
    mint_state: Mint @mut,
    source_account: TokenAccount @mut,
    owner: account @signer,
    amount: u64
) {
    require(source_account.owner_key == owner, "Source account owner mismatch");
    require(source_account.bal >= amount, "Insufficient balance to burn");
    require(source_account.mint == get_key(mint_state), "Source account mint mismatch");
    require(!source_account.is_frozen, "Source account is frozen");

    mint_state.supply = mint_state.supply - amount;
    source_account.bal = source_account.bal - amount;
}

// Freeze a token account
freeze_account(
    mint_state: Mint,
    account_to_freeze: TokenAccount @mut,
    freeze_authority: account @signer
) {
    require(mint_state.freeze_authority == freeze_authority, "Freeze authority mismatch");
    require(account_to_freeze.mint == get_key(mint_state), "Account mint mismatch");
    account_to_freeze.is_frozen = true;
}

// Thaw a token account
thaw_account(
    mint_state: Mint,
    account_to_thaw: TokenAccount @mut,
    freeze_authority: pubkey @signer
) {
    require(mint_state.freeze_authority == freeze_authority, "Freeze authority mismatch");
    require(account_to_thaw.mint == get_key(mint_state), "Account mint mismatch");
    account_to_thaw.is_frozen = false;
}

// Close a token account and reclaim rent (owner must be signer)
close_account(
    source_account: TokenAccount @mut,
    owner: pubkey @signer
) {
    require(source_account.owner_key == owner, "Account owner mismatch");
    require(source_account.bal == 0, "Account must have zero balance to close");
    // In a real VM, this would involve transferring lamports back and marking account as closed/uninitialized
    // For now, we just set balance to 0 and conceptually "close" it.
    source_account.bal = 0;
}

// Change mint authority
set_mint_authority(
    mint_state: Mint @mut,
    current_authority: pubkey @signer,
    new_authority: pubkey
) {
    require(mint_state.authority == current_authority, "Current mint authority mismatch");
    mint_state.authority = new_authority;
}

// Change freeze authority
set_freeze_authority(
    mint_state: Mint @mut,
    current_freeze_authority: pubkey @signer,
    new_freeze_authority: pubkey
) {
    require(mint_state.freeze_authority == current_freeze_authority, "Current freeze authority mismatch");
    mint_state.freeze_authority = new_freeze_authority;
}

// Read-only helpers
get_supply(state: Mint) -> u64 { return state.supply; }
get_balance(state: TokenAccount) -> u64 { return state.bal; }
is_account_frozen(state: TokenAccount) -> bool { return state.is_frozen; }

// Note on Associated Token Accounts (ATAs):
// In a full SPL-like implementation, TokenAccount addresses are often derived
// using a PDA (Program Derived Address) from the owner's pubkey and the mint's pubkey.
// This would typically involve a 'derive_pda' function call during account initialization
// and lookup. The current 'TokenAccount' is a direct account for simplicity.