// five-org/five-protocol/src/test_fixtures.rs
// Golden Fixtures for Parser/Verifier Coverage Tests
//
// This module provides runtime-generated bytecode samples that exercise:
// - Valid headers and instructions
// - Invalid CALL targets (out-of-bounds function indices)
// - VLE truncation (incomplete variable-length encoding)
//
// These fixtures are built at runtime using BytecodeBuilder to avoid raw byte
// constants and ensure tests reflect the canonical builder behavior. They are
// exported behind the "test-fixtures" feature for use in integration tests
// (e.g., five-solana verifier alignment).

use crate::{BytecodeBuilder, JUMP};

/// Return a valid header bytecode with minimal content: header + HALT
pub fn valid_header() -> alloc::vec::Vec<u8> {
    let mut b = BytecodeBuilder::new();
    b.emit_header(1, 2);
    b.emit_halt();
    b.build()
}

/// Return invalid CALL target bytecode: CALL to function index 5 (total functions = 2)
pub fn invalid_call_target() -> alloc::vec::Vec<u8> {
    let mut b = BytecodeBuilder::new();
    b.emit_header(1, 2);
    b.emit_call(5, 0); // 3-byte call to out-of-bounds address
    b.build()
}

/// Return bytecode with truncated VLE: CALL opcode followed by incomplete VLE encoding
pub fn vle_truncation() -> alloc::vec::Vec<u8> {
    let mut b = BytecodeBuilder::new();
    b.emit_header(1, 2);
    b.emit_opcode(JUMP);
    // Emit only the first byte of VLE encoding for value 128 (normally 2 bytes: 0x80, 0x01)
    b.emit_partial_vle_u32(128, 1);
    b.build()
}
