// five-org/five-protocol/src/test_fixtures.rs
// Golden Fixtures for Parser/Verifier Coverage Tests
//
// This module provides runtime-generated bytecode samples that exercise:
// - Valid headers and instructions
// - Invalid CALL targets (out-of-bounds function indices)
// - Operand truncation (incomplete fixed-size operand)
//
// These fixtures are built at runtime using BytecodeBuilder to avoid raw byte
// constants and ensure tests reflect the canonical builder behavior. They are
// exported behind the "test-fixtures" feature for use in integration tests
// (e.g., five-solana verifier alignment).

use alloc::string::String;
use crate::{
    execute_payload::{canonical_execute_payload, TypedParam},
    types, BytecodeBuilder, JUMP,
};

/// Return a valid header bytecode with minimal content: header + HALT
pub fn valid_header() -> alloc::vec::Vec<u8> {
    let mut b = BytecodeBuilder::new();
    b.emit_header(1, 2);
    b.emit_halt();
    b.build()
}

/// Return invalid CALL target bytecode: CALL to address 200 (outside bytecode bounds)
pub fn invalid_call_target() -> alloc::vec::Vec<u8> {
    let mut b = BytecodeBuilder::new();
    b.emit_header(1, 2);
    b.emit_call(200, 0); // 3-byte call to out-of-bounds address
    b.build()
}

/// Return bytecode with truncated operand: JUMP opcode followed by 1 byte (expects 2)
pub fn operand_truncation() -> alloc::vec::Vec<u8> {
    let mut b = BytecodeBuilder::new();
    b.emit_header(1, 2);
    b.emit_opcode(JUMP);
    // Emit only 1 byte of the 2-byte JUMP offset
    b.emit_u8(0);
    b.build()
}

fn push_u32_le(out: &mut alloc::vec::Vec<u8>, value: u32) {
    out.extend_from_slice(&value.to_le_bytes());
}

/// Minimal execute payload in canonical fixed-width format:
/// [function_index:u32 LE][param_count:u32 LE]
pub fn execute_payload_minimal() -> alloc::vec::Vec<u8> {
    canonical_execute_payload(0, &[])
}

/// Canonical typed execute payload:
/// [function_index:u32][param_count:u32]
/// then N params encoded as [type_id][fixed-or-length-prefixed bytes].
pub fn execute_payload_typed_sample() -> alloc::vec::Vec<u8> {
    canonical_execute_payload(
        2,
        &[
            TypedParam::U64(42),
            TypedParam::Bool(true),
            TypedParam::String(String::from("hi")),
            TypedParam::Pubkey([7u8; 32]),
            TypedParam::Account(3),
        ],
    )
}

/// Invalid payload: function index truncated (requires 4 bytes).
pub fn execute_payload_truncated_function_index() -> alloc::vec::Vec<u8> {
    alloc::vec![0x01, 0x02, 0x03]
}

/// Invalid payload: truncated parameter count (requires 4 bytes).
pub fn execute_payload_truncated_param_count() -> alloc::vec::Vec<u8> {
    let mut out = alloc::vec::Vec::new();
    push_u32_le(&mut out, 1);
    out.extend_from_slice(&[0xAA, 0xBB]); // short param_count
    out
}

/// Invalid payload: parameter claims U64 but value is truncated.
pub fn execute_payload_truncated_u64_param() -> alloc::vec::Vec<u8> {
    let mut out = alloc::vec::Vec::new();
    push_u32_le(&mut out, 1);
    push_u32_le(&mut out, 1);
    out.push(types::U64);
    out.extend_from_slice(&[0x11, 0x22, 0x33, 0x44]); // short u64
    out
}

/// Invalid payload: unsupported/unknown type id.
pub fn execute_payload_unknown_type() -> alloc::vec::Vec<u8> {
    let mut out = alloc::vec::Vec::new();
    push_u32_le(&mut out, 1);
    push_u32_le(&mut out, 1);
    out.push(0xFF);
    out.extend_from_slice(&0u64.to_le_bytes());
    out
}
