//! Codegen error templates
//!
//! This module contains templates for code generation related errors,
//! including bytecode generation, optimization, and runtime issues.

use crate::error::templates::{
    ConditionalTemplate, SimpleTemplate, TemplateCondition, TemplateManager,
};

/// Register all codegen error templates
pub fn register_templates(manager: &mut TemplateManager) {
    register_bytecode_templates(manager);
    register_runtime_templates(manager);
    register_optimization_templates(manager);
    register_resource_templates(manager);
}

/// Register bytecode generation templates
fn register_bytecode_templates(manager: &mut TemplateManager) {
    // Invalid opcode
    manager.register(SimpleTemplate::new(
        "invalid_opcode",
        "invalid opcode `{opcode}` in bytecode generation\n\nNote: this is likely a compiler bug\nhelp: please report this issue with the source code that triggered it".to_string(),
    ));

    // Stack overflow in generation
    let stack_overflow_template = ConditionalTemplate::new(
        "stack_overflow_codegen",
        "stack overflow during code generation".to_string(),
    )
    .add_condition(TemplateCondition::new(
        "stack overflow during code generation: expression too complex\n\nhelp: try breaking the expression into smaller parts using intermediate variables\n\nExample:\n  let temp1 = first_part;\n  let temp2 = second_part;\n  let result = temp1 + temp2;".to_string(),
        |ctx| ctx.data.get("cause").map(|c| c.contains("expression")).unwrap_or(false),
    ))
    .add_condition(TemplateCondition::new(
        "stack overflow during code generation: recursive function calls\n\nhelp: Five VM has a limited call stack\nConsider iterative approaches or reducing recursion depth".to_string(),
        |ctx| ctx.data.get("cause").map(|c| c.contains("recursion")).unwrap_or(false),
    ));

    manager.register(stack_overflow_template);

    // Register allocation error
    manager.register(SimpleTemplate::new(
        "register_allocation_failed",
        "register allocation failed for expression\n\nNote: Five VM ran out of available registers\nhelp: try simplifying the expression or using fewer intermediate values\n\nTip: Five VM has 32 registers available for complex calculations".to_string(),
    ));

    // Bytecode size limit
    manager.register(SimpleTemplate::new(
        "bytecode_size_limit",
        "generated bytecode exceeds size limit: {size} bytes (max: {limit} bytes)\n\nhelp: try reducing script complexity:\n  • Split large functions into smaller ones\n  • Remove unused code\n  • Optimize expressions\n\nNote: Solana programs have a 10MB limit, but smaller is better for CU efficiency".to_string(),
    ));
}

/// Register runtime error templates
fn register_runtime_templates(manager: &mut TemplateManager) {
    // Stack underflow
    manager.register(SimpleTemplate::new(
        "stack_underflow",
        "stack underflow: attempted to pop from empty stack\n\nNote: this indicates a compiler bug in stack management\nhelp: please report this with the code that triggered it".to_string(),
    ));

    // Invalid memory access
    let memory_access_template = ConditionalTemplate::new(
        "invalid_memory_access",
        "invalid memory access at runtime".to_string(),
    )
    .add_condition(TemplateCondition::new(
        "invalid memory access: array bounds check failed\n\nThe program attempted to access index {index} of array with length {length}\n\nhelp: ensure array accesses are within bounds\nConsider adding bounds checks in your Five code".to_string(),
        |ctx| ctx.data.contains_key("index") && ctx.data.contains_key("length"),
    ))
    .add_condition(TemplateCondition::new(
        "invalid memory access: null pointer dereference\n\nThe program attempted to access memory through a null pointer\n\nhelp: check that all pointers are properly initialized".to_string(),
        |ctx| ctx.data.get("cause").map(|c| c.contains("null")).unwrap_or(false),
    ));

    manager.register(memory_access_template);

    // Division by zero
    manager.register(SimpleTemplate::new(
        "division_by_zero",
        "division by zero detected at runtime\n\nExpression: {expression}\n\nhelp: add a check to ensure the divisor is not zero\n\nExample:\n  if divisor != 0 {\n      result = dividend / divisor;\n  }".to_string(),
    ));

    // Integer overflow
    manager.register(SimpleTemplate::new(
        "integer_overflow",
        "integer overflow in operation: {operation}\n\nThe result exceeds the maximum value for type `{type}`\n\nhelp: use checked arithmetic or a larger integer type\n\nExample:\n  • Use `checked_add()`, `checked_mul()`, etc.\n  • Use `u64` instead of `u32` if possible".to_string(),
    ));
}

/// Register optimization error templates  
fn register_optimization_templates(manager: &mut TemplateManager) {
    // Optimization failed
    let optimization_failed_template = ConditionalTemplate::new(
        "optimization_failed",
        "optimization pass failed: {pass_name}".to_string(),
    )
    .add_condition(TemplateCondition::new(
        "optimization pass failed: {pass_name}\n\nDead code elimination could not proceed\n\nNote: this is usually safe to ignore, but may result in larger bytecode".to_string(),
        |ctx| ctx.data.get("pass_name").map(|p| p.contains("dead_code")).unwrap_or(false),
    ))
    .add_condition(TemplateCondition::new(
        "optimization pass failed: {pass_name}\n\nConstant folding encountered an error\n\nhelp: check for complex constant expressions that might overflow".to_string(),
        |ctx| ctx.data.get("pass_name").map(|p| p.contains("constant_fold")).unwrap_or(false),
    ));

    manager.register(optimization_failed_template);

    // Inlining failed
    manager.register(SimpleTemplate::new(
        "inlining_failed",
        "function inlining failed for `{function_name}`\n\nReason: {reason}\n\nNote: the function will be called normally instead\nThis may slightly impact performance but is not an error".to_string(),
    ));

    // Loop optimization
    manager.register(SimpleTemplate::new(
        "loop_optimization_failed",
        "loop optimization failed for loop at line {line}\n\nReason: {reason}\n\nhelp: complex loops may not be optimized\nConsider simplifying loop conditions or bounds".to_string(),
    ));
}

/// Register resource limit templates
fn register_resource_templates(manager: &mut TemplateManager) {
    // Compute unit limit
    let cu_limit_template = ConditionalTemplate::new(
        "compute_unit_limit",
        "compute unit limit exceeded: estimated {estimated} CU (limit: {limit} CU)".to_string(),
    )
    .add_condition(TemplateCondition::new(
        "compute unit limit exceeded: estimated {estimated} CU (limit: {limit} CU)\n\nThe script will likely fail on Solana due to compute budget\n\nhelp: optimize your code:\n  • Reduce loop iterations\n  • Simplify complex expressions\n  • Use more efficient algorithms\n  • Consider breaking into multiple transactions".to_string(),
        |ctx| {
            ctx.data.get("estimated")
                .and_then(|e| e.parse::<u32>().ok())
                .map(|e| e > 200_000)
                .unwrap_or(false)
        },
    ));

    manager.register(cu_limit_template);

    // Stack depth limit
    manager.register(SimpleTemplate::new(
        "stack_depth_limit",
        "stack depth limit exceeded: {depth} (max: {limit})\n\nThe call stack is too deep for Five VM\n\nhelp: reduce recursion depth or use iterative approaches\n\nNote: Five VM limits stack depth to prevent infinite recursion".to_string(),
    ));

    // Memory limit
    manager.register(SimpleTemplate::new(
        "memory_limit",
        "memory usage limit exceeded: {usage} bytes (limit: {limit} bytes)\n\nThe script requires too much memory\n\nhelp: optimize memory usage:\n  • Use smaller data types where possible\n  • Process data in chunks\n  • Avoid large temporary allocations".to_string(),
    ));

    // Account limit
    manager.register(SimpleTemplate::new(
        "account_limit",
        "account limit exceeded: {count} accounts (limit: {limit})\n\nThe script tries to access too many accounts\n\nhelp: Solana transactions are limited in the number of accounts they can access\nConsider:\n  • Reducing the number of accounts\n  • Splitting into multiple transactions\n  • Using program-derived addresses (PDAs) more efficiently".to_string(),
    ));
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::types::ErrorContext;
    use std::collections::HashMap;

    #[test]
    fn test_codegen_template_registration() {
        let mut manager = TemplateManager::new();
        register_templates(&mut manager);

        assert!(manager.get("invalid_opcode").is_some());
        assert!(manager.get("stack_overflow_codegen").is_some());
        assert!(manager.get("division_by_zero").is_some());
        assert!(manager.get("compute_unit_limit").is_some());
    }

    #[test]
    fn test_stack_overflow_suggestions() {
        let mut manager = TemplateManager::new();
        register_templates(&mut manager);

        let template = manager.get("stack_overflow_codegen").unwrap();

        // Test expression complexity suggestion
        let mut data = HashMap::new();
        data.insert("cause".to_string(), "expression complexity".to_string());

        let context = ErrorContext::new().with_data(data);
        let rendered = template.render(&context);

        assert!(rendered.contains("intermediate variables"));
        assert!(rendered.contains("temp1"));
    }

    #[test]
    fn test_memory_access_template() {
        let mut manager = TemplateManager::new();
        register_templates(&mut manager);

        let template = manager.get("invalid_memory_access").unwrap();

        // Test bounds check failure
        let mut data = HashMap::new();
        data.insert("index".to_string(), "5".to_string());
        data.insert("length".to_string(), "3".to_string());

        let context = ErrorContext::new().with_data(data);
        let rendered = template.render(&context);

        assert!(rendered.contains("index 5"));
        assert!(rendered.contains("length 3"));
        assert!(rendered.contains("bounds check"));
    }

    #[test]
    fn test_compute_unit_warning() {
        let mut manager = TemplateManager::new();
        register_templates(&mut manager);

        let template = manager.get("compute_unit_limit").unwrap();

        // Test high CU estimate
        let mut data = HashMap::new();
        data.insert("estimated".to_string(), "300000".to_string());
        data.insert("limit".to_string(), "200000".to_string());

        let context = ErrorContext::new().with_data(data);
        let rendered = template.render(&context);

        assert!(rendered.contains("likely fail"));
        assert!(rendered.contains("optimize"));
        assert!(rendered.contains("loop iterations"));
    }

    #[test]
    fn test_optimization_failure_template() {
        let mut manager = TemplateManager::new();
        register_templates(&mut manager);

        let template = manager.get("optimization_failed").unwrap();

        // Test dead code elimination failure
        let mut data = HashMap::new();
        data.insert("pass_name".to_string(), "dead_code_elimination".to_string());

        let context = ErrorContext::new().with_data(data);
        let rendered = template.render(&context);

        assert!(rendered.contains("Dead code elimination"));
        assert!(rendered.contains("safe to ignore"));
    }
}
